#!/bin/sh

. lib/shable

_reign="${1}"
if [ -z "${_reign}" ]; then
    error "No arguments given, with reign names to invoke!"
fi
debug "Reign to be invoked: $(distd "${_reign}")"

_hosts=$(inventory_hosts "${DEFAULT_INVENTORY}")
note "Calling reign: $(distn "${_reign}") on hosts: $(distd "$(echo "${_hosts}" | ${TR_BIN} '\n' ' ' 2>/dev/null)")"

for _host in ${_hosts}; do
    progress_note "Invoking reign: $(distn "${_reign}") for host: $(distn "${_host}")"
    bin/reign "${DEFAULT_INVENTORY}" "${_reign}" "${_host}"
done
