#!/bin/sh

. lib/shable

include "base"


_reign="${1}"
if [ -z "${_reign}" ]; then
    error "No arguments given, with reign names to invoke!"
fi
debug "Reign to be invoked: $(distd "${_reign}")"

if [ "Darwin" = "${SYSTEM_NAME}" ]; then
    _cmd="sudo -H RUN_AS=root bin/shable inventory setup-macos-limits"
    _current_openfiles_max="$(launchctl limit maxfiles | ${AWK_BIN} '{print $2;}' 2>/dev/null)"
    if [ "256" = "${_current_openfiles_max}" ]; then
        warn "Shable detected system type: $(distw "Darwin") with default limits set."
        warn "If you experience problems with multiple asynchronous SSH connections at once,"
        warn "please invoke this on your workstation: $(distw "${_cmd}")."
        warn "This will persistently increase default system limits."
    fi
fi

_hosts=$(inventory_hosts "${DEFAULT_INVENTORY}")
note "Calling reign: $(distn "${_reign}") on hosts: $(distd "$(echo "${_hosts}" | ${TR_BIN} '\n' ' ' 2>/dev/null)")"

unset _process_logs
for _host in ${_hosts}; do
    _log="${DEFAULT_LOGDIR}/reign-${_reign}-on-${_host}.log"
    _process_logs="${_log} ${_process_logs}"
    echo > "${_log}" # Clean previous log

    progress_note "Invoking reign: $(distn "${_reign}") for host: $(distn "${_host}")"
    bin/reign "${DEFAULT_INVENTORY}" "${_reign}" "${_host}" >> "${_log}" 2>> "${_log}" &
done

await_async "${_process_logs}"
