#!/bin/sh

. lib/shable

include "base"


_host="${1}"
_ssh_port="22"

inventory_read "${DEFAULT_INVENTORY}" "${_host}"

not_empty "${_host}" "Specify $(diste "host") to invoke $(diste "base-system-setup") on"
not_empty "${ip}" "Expected defined value of $(diste "ip") in inventory: $(diste "${DEFAULT_INVENTORY}")"
not_empty "${remote_vpn_server}" "Expected defined value of $(diste "remote_vpn_server") in inventory: $(diste "${DEFAULT_INVENTORY}")"


add_ssh_conf_entry "${_host}" "${ip}"
add_ssh_known_host "${ip}"

# handle interrupts - to avoid mess under ~/.ssh/config
trap "remove_last_ssh_conf_entry" INT TERM

note "Setting up new base system on host: $(distn "${_host}"), ip: $(distn "${ip}"), internal ip: $(distn "${remote_vpn_server}")"

# call setup-new-server reign, run as superuser, skip validation of unavailable binaries in pre-base-system:
RUN_AS=root \
SKIP_ENV_VALIDATION=YES \
    bin/reign \
    "${DEFAULT_INVENTORY}" \
    setup-new-dedicated-server \
    "${_host}" \
    "${_ssh_port}"

# after setup, generate new host config
remove_last_ssh_conf_entry
add_ssh_conf_entry "${_host}" "${ip}" "${DEFAULT_SSH_PORT}"
