#!/bin/sh

SH_BIN="/bin/sh"
PATH="/bin:/usr/bin:/sbin:/usr/sbin"
_custody_path="/Shared/Custody"


traverse_custody () {
    for _entry_file in $(find "${_custody_path}" -type f -maxdepth 1 2>/dev/null); do
        _name="${_entry_file##*/}" # basename()
        if [ -n "${_name}" ]; then
            _key="$(cat "${_entry_file}" 2>/dev/null)"
            if [ -z "${_key}" ]; then
                echo; echo "No ssh-key found in contents of file: ${_entry_file}. Jail creation aborted!"
            else
                echo; echo "New custody subject: ${_name}. SSH-ED25519 pubkey: ${_key}"
                ${SH_BIN} -c "gvr create ${_name}" && \
                    ${SH_BIN} -c "gvr set ${_name} key='${_key}'" && \
                        rm -f "${_entry_file}" \
                        echo "Created instance: ${_name}"
            fi
        else
            echo; echo "Empty NAME. Skipped entry: ${_entry_file}"
        fi
    done
}


echo "Custody enters the endless loop on: $(date +%F-%H%M-%s 2>/dev/null)"
while true; do
    traverse_custody
    sleep 2
done
