#!/bin/sh

failure () {
    echo "Openvpn init failed. Network not reachable?"
    exit 1
}


restart_openvpn () {
    _pid="$(cat "{{ openvpn_servicedir }}/service.pid" 2>/dev/null)"
    if [ -n "${_pid}" ]; then
        echo "Openvpn pid: ${_pid}"
        kill -INT "${_pid}" 2>/dev/null
        sleep 1
        kill -TERM "${_pid}" 2>/dev/null
        sleep 2
        kill -KILL "${_pid}" 2>/dev/null
    else
        # Allowed, since we use a single OpenVPN instance per server backend:
        killall -TERM openvpn 2>/dev/null
        killall -KILL openvpn 2>/dev/null
        sleep 2
    fi
    echo "Stopping OpenVPN"
    ifconfig "{{ default_vpn_device }}" destroy 2>/dev/null

    echo "Starting OpenVPN"
    "{{ openvpn_softwaredir }}/exports/openvpn" \
      --config "{{ openvpn_servicedir }}/service.conf" \
      --writepid "{{ openvpn_servicedir }}/service.pid" \
      --daemon "openvpn" && \
        sleep 5 && \
        ifconfig "{{ default_bridge_device }}" addm "{{ default_vpn_device }}" up && \
        ifconfig "{{ default_bridge_device }}" up
}


# main():
restart_openvpn || \
    failure
