#!/bin/sh

reload_or_restart_unbound () {
    _pid="$(cat "{{ unbound_servicedir }}/service.pid" 2>/dev/null)"
    if [ -n "${_pid}" ]; then
        # If "pid is alive" trick with -0 signal:
        kill -0 "${_pid}" 2>/dev/null
        if [ "0" = "${?}" ]; then # if "0" => pid is alive
            echo "Reloading Unbound with pid: ${_pid}"
            kill -HUP "${_pid}" 2>/dev/null
            sleep 1
        else
            echo "Starting Unbound"
            "{{ unbound_softwaredir }}/exports/unbound" -c \
                "{{ unbound_servicedir }}/service.conf"
        fi
    fi
}


test_unbound () {
    "{{ unbound_softwaredir }}/exports/unbound-checkconf"
}


# main():
test_unbound && \
    reload_or_restart_unbound
