#!/bin/sh


restart_unbound () {
    _pid="$(cat "{{ unbound_servicedir }}/service.pid" 2>/dev/null)"
    if [ -n "${_pid}" ]; then
        echo "Found Unbound pid: ${_pid}"
        kill -INT "${_pid}" 2>/dev/null
        sleep 1
        kill -TERM "${_pid}" 2>/dev/null
        sleep 2
        kill -KILL "${_pid}" 2>/dev/null
    else
        # Allowed, since we use a single Unbound instance per server backend:
        killall -TERM unbound 2>/dev/null
        killall -KILL unbound 2>/dev/null
        sleep 2
    fi

    /usr/local/bin/startdns
}


chech_unbound () {
    # DNS check using local DNS:
    drill "google.com" @127.0.0.1 >/dev/null || \
        restart_unbound
}


# main():
chech_unbound
