#!/bin/sh


check_nginx () {
    _pid="$(cat "{{ nginx_servicedir }}/service.pid" 2>/dev/null)"
    if [ -z "${_pid}" ]; then
        rm -f "{{ nginx_servicedir }}/service.pid"
        /usr/local/bin/startnginx
    else
        kill -0 "${_pid}" || \
            /usr/local/bin/startnginx
    fi
}


# main():
check_nginx
