#!/bin/sh

set +e


restart_nginx () {
    _pid="$(cat "{{ nginx_servicedir }}/service.pid" 2>/dev/null)"
    if [ -n "${_pid}" ]; then
        echo "Found Nginx pid: ${_pid}"
        kill -TERM "${_pid}" 2>/dev/null
        kill -KILL "${_pid}" 2>/dev/null
        killall -KILL nginx 2>/dev/null
    else
        killall -TERM nginx 2>/dev/null
        killall -KILL nginx 2>/dev/null
    fi
    sleep 1
    /usr/local/bin/startnginx
}


# main()
_pid="$(cat "{{ nginx_servicedir }}/service.pid" 2>/dev/null)"
if [ -z "${_pid}" ]; then
    restart_nginx
else
    kill -0 "${_pid}" || restart_nginx
fi
