#!/bin/sh

SHABLE_NAME="Shable"
SHABLE_VERSION="0.12.21"

# definitions
DEFAULT_TIMEOUT_S="5" # interval between each failed reign to retry in seconds
PATH="/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin"
DEFAULT_LANG="en_US.UTF-8"
REPLAY_PREVIOUS_LINE="\033[A\33[2K\r"
DEFAULT_SSH_PORT="60022"
DEFAULT_CACHE_FACTS_DIR="facts/cached"
DEFAULT_CACHE_FILE_LOCAL="facts/cached/local.facts"
DEFAULT_LOGDIR="${HOME}/.shable/logs"
DEFAULT_WORKER_USER="worker"

DEFAULT_HOST="localhost"
DEFAULT_INVENTORY_GROUP="default"
DEFAULT_INVENTORY="inventory:${DEFAULT_INVENTORY_GROUP}"

# system specific
HOST_NAME="$(hostname -s)"
SYSTEM_NAME="$(uname)"
SYSTEM_ARCH="$(uname -m)"

# shell specific:
LANG="${DEFAULT_LANG}"
LANGUAGE="${DEFAULT_LANG}"
LC_ALL="${DEFAULT_LANG}"
LC_TIME="${DEFAULT_LANG}"
LC_MONETARY="${DEFAULT_LANG}"
LC_CTYPE="${DEFAULT_LANG}"
LC_COLLATE="${DEFAULT_LANG}"
LC_MESSAGES="${DEFAULT_LANG}"
LC_NUMERIC="${DEFAULT_LANG}"


# binaries
SWAPOFF_BIN="/sbin/swapoff"
SEQ_BIN="/usr/bin/seq"
ENV_BIN="/usr/bin/env"
OPENSSL_BIN="/usr/bin/openssl"
DATE_BIN="/bin/date"
SED_BIN="/bin/sed"
OD_BIN="/usr/bin/od"
GREP_BIN="/bin/grep"
TR_BIN="/usr/bin/tr"
CAT_BIN="/bin/cat"
AWK_BIN="/usr/bin/awk"
HOSTNAME_BIN="/bin/hostname"
SSH_BIN="/usr/bin/ssh"
SCP_BIN="/usr/bin/scp"
LN_BIN="/bin/ln"
RM_BIN="/bin/rm"
HEAD_BIN="/usr/bin/head"
MYSQL_BIN="/usr/bin/mysql"
CUT_BIN="/usr/bin/cut"
MV_BIN="/bin/mv"
INSTALL_BIN="/usr/bin/install"
CURL_BIN="/usr/bin/curl"
CHMOD_BIN="/bin/chmod"
UNZIP_BIN="/usr/bin/unzip"
CP_BIN="/bin/cp"
SYSCTL_BIN="/sbin/sysctl"
UUIDGEN_BIN="/usr/bin/uuidgen"
CHOWN_BIN="/bin/chown"
SORT_BIN="/usr/bin/sort"
UNIQ_BIN="/usr/bin/uniq"
GIT_BIN="/usr/bin/git"
TOUCH_BIN="/usr/bin/touch"
TAIL_BIN="/usr/bin/tail"
SSHKEYGEN_BIN="/usr/bin/ssh-keygen"
SSHKEYSCAN_BIN="/usr/bin/ssh-keyscan"
DIG_BIN="/usr/bin/dig"
WC_BIN="/usr/bin/wc"
BC_BIN="/usr/bin/bc"
RSYNC_BIN="/usr/bin/rsync"
ID_BIN="/usr/bin/id"
FIND_BIN="/usr/bin/find"
IFCONFIG_BIN="/sbin/ifconfig"
PS_BIN="/bin/ps"

# system specific paths
case "${SYSTEM_NAME}" in
    Darwin|FreeBSD)
        GREP_BIN="/usr/bin/grep"
        SED_BIN="/usr/bin/sed"
        SYSCTL_BIN="/usr/sbin/sysctl"
        CHOWN_BIN="/usr/sbin/chown"
        if [ -x "/usr/local/bin/mysql" ]; then
            # brew, Darwin:
            MYSQL_BIN="/usr/local/bin/mysql"
        elif [ -x "/Software/Mariadb/exports/mysql" ]; then
            # sofin, FreeBSD|Darwin:
            MYSQL_BIN="/Software/Mariadb/exports/mysql"
        else
            # no mysql client available, just unset it to avoid validate_env() failure:
            unset MYSQL_BIN
        fi
        if [ -x "/usr/bin/pass" ]; then
            # apt, Linux:
            PASS_BIN="/usr/bin/pass"
        elif [ -x "/usr/local/bin/pass" ]; then
            # brew, Darwin:
            PASS_BIN="/usr/local/bin/pass"
        elif [ -x "/Software/Pass/exports/pass" ]; then
            # sofin, FreeBSD|Darwin:
            PASS_BIN="/Software/Pass/exports/pass"
        else
            # no mysql client available, just unset it to avoid validate_env() failure:
            unset PASS_BIN
        fi

        if [ -x "/usr/bin/curl" ]; then
            CURL_BIN="/usr/bin/curl"
        elif [ -x "/Software/Curl/exports/curl" ]; then
            CURL_BIN="/Software/Curl/exports/curl"
        else
            # XXX: set fallback to first available under production OS:
            CURL_BIN="/Software/Curl/exports/curl"
        fi

        if [ -x "/usr/bin/zfs" ]; then
            ZFS_BIN="/usr/bin/zfs"
        fi
        ;;

    Linux)
        if [ -x "/usr/bin/pass" ]; then
            # apt, Linux:
            PASS_BIN="/usr/bin/pass"
        elif [ -x "/usr/local/bin/pass" ]; then
            # brew, Darwin:
            PASS_BIN="/usr/local/bin/pass"
        else
            # no mysql client available, just unset it to avoid validate_env() failure:
            unset PASS_BIN
        fi
        USERMOD_BIN="/usr/sbin/usermod"
        ;;

    Minix)
        USERMOD_BIN="/usr/sbin/usermod"

        RSYNC_BIN="/usr/pkg/bin/rsync"
        GIT_BIN="/usr/pkg/bin/git"
        CURL_BIN="/usr/pkg/bin/curl"

        unset PASS_BIN
        unset SYSCTL_BIN
        ;;

esac


# FreeBSD specific:
case "${SYSTEM_NAME}" in
    FreeBSD)
        SYSCTL_BIN="/sbin/sysctl"
        UUIDGEN_BIN="/bin/uuidgen"
        GIT_BIN="/Software/Git/exports/git"
        RSYNC_BIN="/Software/Rsync/exports/rsync"
        DRILL_BIN="/usr/bin/drill"
        HOST_BIN="/usr/bin/host"
        unset DIG_BIN
        ;;

    Darwin)
        unset SWAPOFF_BIN
        ;;

esac


# Special chars:
NoteChar="»"

# Use legacy ANSI definitions:
ColorGray="\033[39m" # default color of terminal
ColorReset="${ColorGray}"
ColorDarkgray="\033[90m"
ColorRed="\033[31m"
ColorGreen="\033[32m"
ColorYellow="\033[33m"
ColorOrange="\033[38;5;172m"
ColorBlue="\033[34m"
ColorMagenta="\033[35m"
ColorCyan="\033[36m"
ColorDistinct="${ColorCyan}"
ColorWhite="\033[97m"
ColorParams="\033[38;5;12m"
ColorViolet="\033[38;5;97m"
ColorDebug="${ColorViolet}"
ColorNote="${ColorGreen}"
ColorWarning="${ColorYellow}"
ColorError="${ColorRed}"
ColorExample="${ColorOrange}"
ColorFunction="\033[38;5;163m"
