#!/bin/sh

failure () {
    echo "Openvpn init failed. Network not reachable?"
    exit 1
}


restart_openvpn () {
    _pid="$(cat "{{ openvpn_servicedir }}/service.pid" 2>/dev/null)"
    if [ -n "${_pid}" ]; then
        echo "Found Openvpn pid: ${_pid}"
        kill -TERM "${_pid}" 2>/dev/null
        kill -KILL "${_pid}" 2>/dev/null
        killall -KILL openvpn 2>/dev/null
    else
        killall -TERM openvpn 2>/dev/null
        killall -KILL openvpn 2>/dev/null
    fi
    echo "Stopping OpenVPN"
    sleep 2
    ifconfig "{{ default_vpn_device }}" destroy 2>/dev/null

    echo "Starting OpenVPN"
    "{{ openvpn_softwaredir }}/exports/openvpn" \
      --config "{{ openvpn_servicedir }}/service.conf" \
      --daemon "openvpn" \
      --writepid "{{ openvpn_servicedir }}/service.pid"

    # wait for new route to be estabilished:
    sleep 5

    ifconfig "{{ default_bridge_device }}" addm "{{ default_vpn_device }}" up
    ifconfig "{{ default_bridge_device }}" up
}


# main():
restart_openvpn || failure
