#!/bin/sh

set +e
export PATH="/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:{{ openvpn_softwaredir }}/exports"

_vpn_router="{{ default_vpn_router }}"

restart_openvpn () {
    _pid="$(cat {{ openvpn_servicedir }}/service.pid 2>/dev/null)"
    if [ -n "${_pid}" ]; then
        echo "Found Openvpn pid: ${_pid}"
        kill -TERM ${_pid} 2>/dev/null
        kill -KILL ${_pid} 2>/dev/null
        killall -KILL openvpn 2>/dev/null
    else
        killall -TERM openvpn 2>/dev/null
        killall -KILL openvpn 2>/dev/null
    fi
    sleep 1
    ifconfig {{ default_vpn_device }} destroy 2>/dev/null
    /usr/local/bin/startvpn
}


# main()
ping -t3 -c1 ${_vpn_router} >/dev/null || restart_openvpn
