#!/bin/sh

_oom_value="-1000"

for _proc_name in \
    ntpd \
    sshd \
    cron \
    redis-server \
    mysqld \
    nginx \
    wg-crypt-wg0 \
    filebeat \
    telegraf \
; do
    for _pid in $(pidof "${_proc_name}" 2>/dev/null); do
        _oom_score_file="/proc/${_pid}/oom_score_adj"
        if [ -f "${_oom_score_file}" ]; then
            echo "${_oom_value}" > "${_oom_score_file}"
            logger "Set oom_score_adj: ${_oom_value} for pid: ${_pid} (${_proc_name})"
        fi
    done
done
